# Generated by Django 3.0.3 on 2022-11-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сurrencybase',
            options={'verbose_name': 'база_валют', 'verbose_name_plural': 'база_валюты'},
        ),
        migrations.RemoveField(
            model_name='сurrencybase',
            name='date',
        ),
        migrations.AddField(
            model_name='сurrencybase',
            name='number_of_currency',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
